//
// Created by Dell on 4/28/2024.
//

#ifndef PROJECTSOFTWAREENGINEERINGUA_EMISSIONSMANAGER_H
#define PROJECTSOFTWAREENGINEERINGUA_EMISSIONSMANAGER_H


class EmissionsManager {

};


#endif //PROJECTSOFTWAREENGINEERINGUA_EMISSIONSMANAGER_H
