//
// Created by admin on 4/28/2024.
//

#ifndef PROJECTSOFTWAREENGINEERINGUA_PRINTERSYSTEM_H
#define PROJECTSOFTWAREENGINEERINGUA_PRINTERSYSTEM_H


class PrinterSystem {
public:
    void systemStart();
};


#endif //PROJECTSOFTWAREENGINEERINGUA_PRINTERSYSTEM_H
