//
// Created by Oubay on 29/02/2024.
//

#ifndef PROJECTTITLE_XMLPRINTERSYSTEMREADER_H
#define PROJECTTITLE_XMLPRINTERSYSTEMREADER_H


class XMLPrinterSystemReader {

};


#endif //PROJECTTITLE_XMLPRINTERSYSTEMREADER_H
